{
 "title": "Review Data",
 "time": { "from": "now-7d", "to": "now-2d" },
 "panels": [
  { "title": "Review Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Products Reviewed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT count(DISTINCT asin) FROM amazon_reviews.collected_review_data;"
    }
   ]
  },
  {
   "title": "Total Processed Review",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT count(reviewID) FROM amazon_reviews.collected_review_data;"
    }
   ]
  },
  {
   "title": "Anker Soundcore Mini(Bluetooth Speaker)",
   "type": "timeseries",
   "description": "asin=\"B01HTH3C8S\"",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B01HTH3C8S\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B01HTH3C8S\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B01HTH3C8S\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "Anker Soundcore Mini(Bluetooth Speaker)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B01HTH3C8S\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "Seagate Portable 2TB External Hard Drive Portable HDD",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B07CRG94G3\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "Seagate Portable 2TB External Hard Drive Portable HDD",
   "type": "timeseries",
   "description": "asin=\"B07CRG94G3\"",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B07CRG94G3\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07CRG94G3\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07CRG94G3\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "TP-Link AC750 WiFi Extender (RE220)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B07N1WW638\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "TP-Link AC750 WiFi Extender (RE220)",
   "type": "timeseries",
   "description": "asin=\"B07N1WW638\"",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B07N1WW638\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07N1WW638\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07N1WW638\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "Sleep Headphones Wireless",
   "type": "timeseries",
   "description": "asin=\"B07SHBQY7Z\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B07SHBQY7Z\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07SHBQY7Z\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07SHBQY7Z\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "Amazon Basics Digital Optical Audio Toslink Cable for Sound Bar",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B00NH11H38\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "JBL Flip 5 Portable Waterproof Wireless Bluetooth Speaker",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B07QK2SPP7\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "JBL Flip 5 Portable Waterproof Wireless Bluetooth Speaker",
   "type": "timeseries",
   "description": "asin=\"B07QK2SPP7\"",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B07QK2SPP7\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07QK2SPP7\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07QK2SPP7\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "Sleep Headphones Wireless",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B07SHBQY7Z\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "JBL GO2 Ultra Portable Waterproof Wireless Bluetooth Speaker",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B07SJTHHRB\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "JBL GO2 Ultra Portable Waterproof Wireless Bluetooth Speaker",
   "type": "timeseries",
   "description": "asin=\"'B07SJTHHRB'\"",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B0BCN4FXD5\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07SJTHHRB\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B07SJTHHRB\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "Chromecast with Google TV (HD)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B0BCN4FXD5\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "Anker Soundcore Bluetooth Speaker",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B016XTADG2\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "Chromecast with Google TV (HD)",
   "type": "timeseries",
   "description": "asin=\"'B0BCN4FXD5'\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B0BCN4FXD5\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B0BCN4FXD5\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B0BCN4FXD5\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "TP-Link TL-SG105 5 Port Gigabit Unmanaged Ethernet Network Switch",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT sentiment,count(sentiment) FROM amazon_reviews.collected_review_data  where asin=\"B01HTH3C8S\" GROUP BY sentiment;"
    }
   ]
  },
  {
   "title": "Anker Soundcore Bluetooth Speaker",
   "type": "timeseries",
   "description": "asin=\"'B016XTADG2'\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B016XTADG2\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B016XTADG2\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B016XTADG2\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "TP-Link TL-SG105 5 Port Gigabit Unmanaged Ethernet Network Switch",
   "type": "timeseries",
   "description": "asin=\"'B00A128S24'\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B00A128S24\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B00A128S24\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B00A128S24\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  },
  {
   "title": "Amazon Basics Digital Optical Audio Toslink Cable for Sound Bar",
   "type": "timeseries",
   "description": "asin=\"B00NH11H38\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "dataset": "amazon_reviews",
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Total Reviews\" FROM amazon_reviews.collected_review_data  where asin=\"B00NH11H38\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Positive Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B00NH11H38\" AND sentiment = \"Positive\" GROUP BY reviewDate;"
    },
    {
     "rawSql": "SELECT reviewDate, count(reviewID) As \"Other Reviews\"  FROM amazon_reviews.collected_review_data  where asin=\"B00NH11H38\" AND (sentiment = \"Negative\" OR sentiment=\"Neutral\") GROUP BY reviewDate;"
    }
   ]
  }
 ]
}